language: php
php:
  - "5.3"
install:
  - "composer install"
  - "composer self-update"
  - "nohup node tests/server/server.js &"
matrix:
  include:
    - php: 5.3
      dist: precise
script: "bin/phing test"

